# Generated by Django 2.1.4 on 2019-01-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='follows',
            field=models.ManyToManyField(default='None', related_name='follows_users', to='base.Member'),
        ),
    ]
