# Generated by Django 2.1.4 on 2019-01-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190111_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='follows_users', to='base.Member'),
        ),
    ]
