# Generated by Django 2.1.4 on 2019-01-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190112_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='followers',
            new_name='number_of_followers',
        ),
        migrations.AlterField(
            model_name='member',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followers', to='base.Member'),
        ),
    ]
