# Generated by Django 2.1.4 on 2019-01-13 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20190113_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_history',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
