# Generated by Django 2.1.4 on 2019-01-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20190113_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
