# Generated by Django 2.1.4 on 2019-01-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20190116_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='member',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='senders', to='base.Member'),
        ),
    ]
