# Generated by Django 2.1.4 on 2019-01-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20190116_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='receivers',
        ),
        migrations.AddField(
            model_name='member',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='subscriber', to='base.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=60),
        ),
    ]
