# Generated by Django 2.1.4 on 2019-01-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20190119_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(default='/media/default.png', upload_to='propic'),
        ),
    ]
