# Generated by Django 2.1.4 on 2019-01-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20190119_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(default='/home/mr_dush__t/django-dush-t/LiteConnect/LiteConnect/static/default.png', upload_to='propic'),
        ),
    ]
